baseURL = 'https://stuffbymax.me/wiki-blogs/'
title = "wiki"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "win"
preserveTaxonomyNames = true


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "wiki and blogs"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to the early 90s! "
    lastupdate = "last update 2025-05-15 11:48" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "this is a wiki and blogs"

    # Urls for social networks
    source = "https://github.com/stuffbymax/wiki"
    github = "https://github.com/stuffbymax"
    youtube = "https://www.youtube.com/@stuffbymax"
    itch.io = "https://stuff-by-max.itch.io/"
    

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 6.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "stuffbymax|Martin Petik"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://github.com/stuffbymax/wiki-blogs/blob/main/LICENSE"

    # Text to go before copyright information
    prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "MIT License"
    
    # Show the "built on Hugo" disclaimer
    showhugo = true

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar
    
  [[menu.main]]
    identifier = "portfolio" # An unique identifier for the button
    name = "portfolio"       # A display name for the button
    url = "https://stuffbymax.me/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar
    
      [[menu.main]]
    identifier = "cv" # An unique identifier for the button
    name = "cv"       # A display name for the button
    url = "https://stuffbymax.me/cv"      # The path to the content. It can lead to a single page (like here)
    weight = 10         # A number to order the buttons in the navbar
    

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
    
   [privacy.source]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
